name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa automaticamente todo dia à meia-noite (UTC)
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Arthur-Luiz19  # Troque pelo seu usuário do GitHub
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
